### ISSUE TITLE
Extension errors out with "unknown option: 11"

### ISSUE THREAD

**Issue by mislav** [nicovince/gh-fzf-run#1]
```
$ gh extension install nicovince/gh-fzf-run
$ gh fzf-run
unknown option: 11
```
```
bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
```

**Comment by nicovince** [comment]
What is your version of `fzf` ?

I am using `0.29 (devel)`
My guess is that you have an old version for which `--preview-window` option is not compatible with the syntax used in this extension (position,size `down,11`)

**Comment by mislav** [comment]
I just upgraded fzf but the issue still remains:
```
==> Upgrading fzf
  0.33.0 -> 0.41.1
```
I think the issue is with BSD `wc` (I'm on macOS).

There is this expression:
```sh
--preview-window=down,$(echo "${FZF_RUN_HELP}" | wc -l)
```

Since the value to `--preview-window` option isn't shell-quoted, the expression will cause an argument error if the capturing expression produces any whitespace.

It's counter-intuitive, but `wc` on macOS does produce leading whitespace:
<img width="680" alt="image" src="https://github.com/nicovince/gh-fzf-run/assets/887/ecbbd2ec-a706-4454-8bbc-3cc6ad73a750">

So you'll have to trim the whitespace around the number if you plan to pass just the number to fzf.

**Comment by nvincent-vossloh** [comment]
Thanks for your analysis on this issue @mislav,

I have pushed a fix (I hope) for this issue, could you give it a try please ?

```bash
git clone https://github.com/nicovince/gh-fzf-run --branch issue_1/strip_leading_ws_wc
gh extension remove gh-fzf-run
cd gh-fzf-run
gh extension install .
```

**Comment by mislav** [comment]
This solves the `--preview-window` problem but later the extension fails with another problem: undefined function `get_last_arg`.

This is because you `export -f get_last_arg` from your bash script, but fzf is not guaranteed to use bash. Instead, fzf will open the shell that is specified by the `SHELL` environment variable, falling back to `sh` if not set. I use zsh (the default shell for macOS), therefore fzf will also use zsh for me by default, where your `get_last_arg` function will never be available.

You can fix this by instructing fzf spawned by your extension to use bash:
```sh
SHELL="$BASH" fzf ...
```

**Comment by nvincent-vossloh** [comment]
Thanks I have made the suggested modification.

**Comment by mislav** [comment]
Looks good!
